### ISSUE TITLE
Uncaught Error: spawn UNKNOWN

### ISSUE THREAD

**Issue by hillsy** [stefansundin/atom-replace-notepad#1]
[Enter steps to reproduce below:]
1. Click "Packages -> Replace Notepad -> Replace Notepad"
2. Error is immediately thrown
3. Notepad doesn't appear to be replaced (running notepad.exe from command prompt opens Notepad, not Atom)

**Atom Version**: 1.2.3
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [replace-notepad](https://github.com/stefansundin/atom-replace-notepad) package, v0.1.1
### Stack Trace

Uncaught Error: spawn UNKNOWN

```
At internal/child_process.js:298

Error: spawn UNKNOWN
    at exports._errnoException (util.js:837:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at exports.spawn (child_process.js:351:9)
    at Object.module.exports.ReplaceNotepad.replace (file:///C:/Users/shhi2/.atom/packages/replace-notepad/lib/replace-notepad.coffee:16:5)
    at atom-workspace.subscriptions.add.atom.commands.add.replace-notepad:replace (file:///C:/Users/shhi2/.atom/packages/replace-notepad/lib/replace-notepad.coffee:9:91)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\shhi2\AppData\Local\atom\app-1.2.3\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Users\shhi2\AppData\Local\atom\app-1.2.3\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\shhi2\AppData\Local\atom\app-1.2.3\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (C:\Users\shhi2\AppData\Local\atom\app-1.2.3\resources\app.asar\src\atom-environment.js:987:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```
### Commands

```
  3x -3:29.3.0 replace-notepad:replace (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
remote-edit, v1.8.22
replace-notepad, v0.1.1

# Dev
No dev packages
```

**Comment by stefansundin** [comment]
Hi. Something probably changed in the recent Atom releases. I'll take a look this weekend. Thanks for reporting!

**Comment by stefansundin** [comment]
I have tried to reproduce the issue with Atom 1.2.3 but I can't get it to trigger.

I have two theories:
- Are you running 32-bit Windows? I'm sorry but right now this only supports 64-bit. I can and should fix this.
- Does the exe file exist? Maybe you have an anti virus that deleted `bin/replace-notepad.exe`?

**Comment by hillsy** [comment]
It's a work laptop; as it's brand new I had assumed it was 64 bit but it
appears to be 32. So that will be the problem.

Thanks

**Comment by stefansundin** [comment]
I pushed a new version (v0.2.0) where everything is 32-bit now. I should have made it 32-bit from the beginning since Atom is 32-bit only right now. Update and let me know how it works for you.
